### ISSUE TITLE
HTTPMock does not work on Python 3.4

### ISSUE THREAD

**Issue by sirmar** [pretenders/pretenders#113]
With python 3.4 I run nosetests on this:

``` python
from pretenders.client.http import HTTPMock

class TestRunner(object):
    def test_me(self):
        HTTPMock('localhost', 80)
```

And get the following error:

```
 File "tests/module/test_runner.py", line 5, in test_me
    HTTPMock('localhost', 80)
  File ".tox/ci/lib/python3.4/site-packages/pretenders/client/http.py", line 49, in __init__
    super(HTTPMock, self).__init__(host, port, timeout, name)
  File ".tox/ci/lib/python3.4/site-packages/pretenders/client/__init__.py", line 95, in __init__
    self.connection = httplib.HTTPConnection(self.full_host, strict=0)
TypeError: __init__() got an unexpected keyword argument 'strict'
```

Python documentation says this:

> Changed in version 3.4: The strict parameter was removed. HTTP 0.9-style “Simple Responses” are not longer supported.

**Comment by txels** [comment]
Thanks for the report, we'll take a look.

**Comment by Insoleet** [comment]
I also got the error.

>
    self.connection = httplib.HTTPConnection(self.full_host, strict=0)
TypeError: __init__() got an unexpected keyword argument 'strict'

Do you know any workaround ?

**Comment by txels** [comment]
We will need to change this to work on python 3.4. In the meantime you would need to use 3.3 at most.

**Comment by Insoleet** [comment]
It looks like pretenders is not compatible with python 3.4...

````
Traceback (most recent call last):
  File "D:\dev\cutecoin\src\cutecoin\tests\process_cfg_community\test_add_community.py", line 36, in test_add_community_empty_blockchain
    mock = new_blockchain.get_mock()
  File "D:\dev\cutecoin\src\cutecoin\tests\mocks\bma\new_blockchain.py", line 76, in get_mock
    headers={'Content-Type': 'application/json'})
  File "D:\Anaconda3_64\lib\site-packages\pretenders\client\http.py", line 103, in reply
    self.preset.add(self.rule, status, body, headers, times, after)
  File "D:\Anaconda3_64\lib\site-packages\pretenders\client\__init__.py", line 70, in add
    body=binary_to_ascii(response_body),
  File "D:\Anaconda3_64\lib\site-packages\pretenders\mock_servers\http\__init__.py", line 38, in binary_to_ascii
    return base64.b64encode(data).decode('ascii')
  File "D:\Anaconda3_64\lib\base64.py", line 62, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: 'str' does not support the buffer interface
```

Do you plan on fixing the compatibility soon or should I fork to fix these problems ?
I'm using some libraries who need python 3.4 to work properly...

**Comment by txels** [comment]
Feel free to fork and send a PR if you have a working solution for both Python3.3 and 3.4.
